steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.buildenv', '-t', 'buildenv', '.']
- name: 'buildenv'
  args: ['-c', 'git submodule update --init --recursive']
- name: 'buildenv'
  args: ['-c', 'make']
- name: 'buildenv'
  args: ['-c', 'make check']
- name: 'buildenv'
  args: ['-c', 'make clean && CXXFLAGS="-fsanitize=address" CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" make check']
